// Dev World Cup (past) — 4 groups, all results final
// Groups: A (Northland, Southfield, Eastbrook, Westmore)
//         B (Redville, Blueton, Greenham, Yellowshore)
//         C (Ironport, Goldfield, Bronzewick, Silverdale)
//         D (Moonhaven, Suncrest, Starfall, Skyreach)
// Playoff: A1=Northland A2=Southfield, B1=Redville B2=Blueton, C1=Ironport C2=Goldfield, D1=Moonhaven D2=Suncrest
// QF: A1vB2, B1vA2, C1vD2, D1vC2 | SF: winner(25)v(26), winner(27)v(28) | Final: winner(29)v(30) → Northland

const past = [
  // ── Group A ──────────────────────────────────────────────────────────────
  { matchNumber: 1,  round: 1, type: "Group", groupName: "A", homeTeamName: "Northland (ENG)",  awayTeamName: "Eastbrook (FRA)",   homeTeamGoals: 2, awayTeamGoals: 1, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-01T13:00:00.000Z"), location: "North Stadium" },
  { matchNumber: 2,  round: 1, type: "Group", groupName: "A", homeTeamName: "Southfield (GER)", awayTeamName: "Westmore (ESP)",    homeTeamGoals: 1, awayTeamGoals: 0, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-01T16:00:00.000Z"), location: "South Arena" },
  { matchNumber: 3,  round: 2, type: "Group", groupName: "A", homeTeamName: "Northland (ENG)",  awayTeamName: "Westmore (ESP)",    homeTeamGoals: 1, awayTeamGoals: 0, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-05T13:00:00.000Z"), location: "North Stadium" },
  { matchNumber: 4,  round: 2, type: "Group", groupName: "A", homeTeamName: "Eastbrook (FRA)",  awayTeamName: "Southfield (GER)",  homeTeamGoals: 1, awayTeamGoals: 1, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-05T16:00:00.000Z"), location: "East Ground" },
  { matchNumber: 5,  round: 3, type: "Group", groupName: "A", homeTeamName: "Northland (ENG)",  awayTeamName: "Southfield (GER)",  homeTeamGoals: 0, awayTeamGoals: 0, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-09T16:00:00.000Z"), location: "North Stadium" },
  { matchNumber: 6,  round: 3, type: "Group", groupName: "A", homeTeamName: "Westmore (ESP)",   awayTeamName: "Eastbrook (FRA)",   homeTeamGoals: 1, awayTeamGoals: 2, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-09T16:00:00.000Z"), location: "West Park" },
  // ── Group B ──────────────────────────────────────────────────────────────
  { matchNumber: 7,  round: 1, type: "Group", groupName: "B", homeTeamName: "Blueton (BRA)",    awayTeamName: "Yellowshore (POR)", homeTeamGoals: 3, awayTeamGoals: 0, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-02T13:00:00.000Z"), location: "Blue Bowl" },
  { matchNumber: 8,  round: 1, type: "Group", groupName: "B", homeTeamName: "Redville (ARG)",   awayTeamName: "Greenham (ITA)",    homeTeamGoals: 2, awayTeamGoals: 1, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-02T16:00:00.000Z"), location: "Red Field" },
  { matchNumber: 9,  round: 2, type: "Group", groupName: "B", homeTeamName: "Blueton (BRA)",    awayTeamName: "Greenham (ITA)",    homeTeamGoals: 1, awayTeamGoals: 1, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-06T13:00:00.000Z"), location: "Blue Bowl" },
  { matchNumber: 10, round: 2, type: "Group", groupName: "B", homeTeamName: "Redville (ARG)",   awayTeamName: "Yellowshore (POR)", homeTeamGoals: 0, awayTeamGoals: 1, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-06T16:00:00.000Z"), location: "Red Field" },
  { matchNumber: 11, round: 3, type: "Group", groupName: "B", homeTeamName: "Blueton (BRA)",    awayTeamName: "Redville (ARG)",    homeTeamGoals: 0, awayTeamGoals: 2, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-10T16:00:00.000Z"), location: "Blue Bowl" },
  { matchNumber: 12, round: 3, type: "Group", groupName: "B", homeTeamName: "Greenham (ITA)",   awayTeamName: "Yellowshore (POR)", homeTeamGoals: 1, awayTeamGoals: 0, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-10T16:00:00.000Z"), location: "Green Dome" },
  // ── Group C ──────────────────────────────────────────────────────────────
  { matchNumber: 13, round: 1, type: "Group", groupName: "C", homeTeamName: "Ironport (USA)",   awayTeamName: "Bronzewick (AUT)",  homeTeamGoals: 2, awayTeamGoals: 0, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-03T13:00:00.000Z"), location: "Iron Arena" },
  { matchNumber: 14, round: 1, type: "Group", groupName: "C", homeTeamName: "Silverdale (RSA)", awayTeamName: "Goldfield (MEX)",   homeTeamGoals: 1, awayTeamGoals: 1, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-03T16:00:00.000Z"), location: "Silver Park" },
  { matchNumber: 15, round: 2, type: "Group", groupName: "C", homeTeamName: "Ironport (USA)",   awayTeamName: "Goldfield (MEX)",   homeTeamGoals: 1, awayTeamGoals: 1, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-07T13:00:00.000Z"), location: "Iron Arena" },
  { matchNumber: 16, round: 2, type: "Group", groupName: "C", homeTeamName: "Silverdale (RSA)", awayTeamName: "Bronzewick (AUT)",  homeTeamGoals: 0, awayTeamGoals: 2, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-07T16:00:00.000Z"), location: "Silver Park" },
  { matchNumber: 17, round: 3, type: "Group", groupName: "C", homeTeamName: "Ironport (USA)",   awayTeamName: "Silverdale (RSA)",  homeTeamGoals: 3, awayTeamGoals: 1, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-11T16:00:00.000Z"), location: "Iron Arena" },
  { matchNumber: 18, round: 3, type: "Group", groupName: "C", homeTeamName: "Goldfield (MEX)",  awayTeamName: "Bronzewick (AUT)",  homeTeamGoals: 2, awayTeamGoals: 0, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-11T16:00:00.000Z"), location: "Gold Field" },
  // ── Group D ──────────────────────────────────────────────────────────────
  { matchNumber: 19, round: 1, type: "Group", groupName: "D", homeTeamName: "Moonhaven (JAP)",  awayTeamName: "Starfall (MOR)",    homeTeamGoals: 2, awayTeamGoals: 1, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-04T13:00:00.000Z"), location: "Moon Dome" },
  { matchNumber: 20, round: 1, type: "Group", groupName: "D", homeTeamName: "Suncrest (KOR)",   awayTeamName: "Skyreach (SAU)",    homeTeamGoals: 1, awayTeamGoals: 0, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-04T16:00:00.000Z"), location: "Sun Bowl" },
  { matchNumber: 21, round: 2, type: "Group", groupName: "D", homeTeamName: "Moonhaven (JAP)",  awayTeamName: "Skyreach (SAU)",    homeTeamGoals: 0, awayTeamGoals: 0, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-08T13:00:00.000Z"), location: "Moon Dome" },
  { matchNumber: 22, round: 2, type: "Group", groupName: "D", homeTeamName: "Suncrest (KOR)",   awayTeamName: "Starfall (MOR)",    homeTeamGoals: 2, awayTeamGoals: 1, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-08T16:00:00.000Z"), location: "Sun Bowl" },
  { matchNumber: 23, round: 3, type: "Group", groupName: "D", homeTeamName: "Moonhaven (JAP)",  awayTeamName: "Suncrest (KOR)",    homeTeamGoals: 1, awayTeamGoals: 0, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-12T16:00:00.000Z"), location: "Moon Dome" },
  { matchNumber: 24, round: 3, type: "Group", groupName: "D", homeTeamName: "Starfall (MOR)",   awayTeamName: "Skyreach (SAU)",    homeTeamGoals: 1, awayTeamGoals: 0, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-12T16:00:00.000Z"), location: "Star Park" },
  // ── Quarter Finals (round=1) ─────────────────────────────────────────────
  { matchNumber: 25, round: 1, type: "Playoff", homeTeamName: "Northland (ENG)", awayTeamName: "Blueton (BRA)",    homeTeamGoals: 2, awayTeamGoals: 0, matchAccepted: true, sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-22T15:00:00.000Z"), location: "North Stadium", getTeamsFrom: { home: { groupName: "A", position: 1 }, away: { groupName: "B", position: 2 } } },
  { matchNumber: 26, round: 1, type: "Playoff", homeTeamName: "Redville (ARG)",  awayTeamName: "Southfield (GER)", homeTeamGoals: 1, awayTeamGoals: 2, matchAccepted: true, sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-22T18:00:00.000Z"), location: "Red Field",     getTeamsFrom: { home: { groupName: "B", position: 1 }, away: { groupName: "A", position: 2 } } },
  { matchNumber: 27, round: 1, type: "Playoff", homeTeamName: "Ironport (USA)",  awayTeamName: "Suncrest (KOR)",   homeTeamGoals: 3, awayTeamGoals: 0, matchAccepted: true, sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-23T15:00:00.000Z"), location: "Iron Arena",    getTeamsFrom: { home: { groupName: "C", position: 1 }, away: { groupName: "D", position: 2 } } },
  { matchNumber: 28, round: 1, type: "Playoff", homeTeamName: "Moonhaven (JAP)", awayTeamName: "Goldfield (MEX)",  homeTeamGoals: 1, awayTeamGoals: 0, matchAccepted: true, sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-06-23T18:00:00.000Z"), location: "Moon Dome",     getTeamsFrom: { home: { groupName: "D", position: 1 }, away: { groupName: "C", position: 2 } } },
  // ── Semi Finals (round=2) ────────────────────────────────────────────────
  { matchNumber: 29, round: 2, type: "Playoff", homeTeamName: "Northland (ENG)", awayTeamName: "Southfield (GER)", homeTeamGoals: 2, awayTeamGoals: 1, matchAccepted: true, sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-07-02T18:00:00.000Z"), location: "North Stadium", getTeamsFrom: { home: { matchNumber: 25 }, away: { matchNumber: 26 } } },
  { matchNumber: 30, round: 2, type: "Playoff", homeTeamName: "Ironport (USA)",  awayTeamName: "Moonhaven (JAP)",  homeTeamGoals: 1, awayTeamGoals: 2, matchAccepted: true, sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-07-03T18:00:00.000Z"), location: "Iron Arena",    getTeamsFrom: { home: { matchNumber: 27 }, away: { matchNumber: 28 } } },
  // ── Final (round=3) ──────────────────────────────────────────────────────
  { matchNumber: 31, round: 3, type: "Playoff", homeTeamName: "Northland (ENG)", awayTeamName: "Moonhaven (JAP)",  homeTeamGoals: 2, awayTeamGoals: 0, matchAccepted: true, sport: "Soccer", bracketCode: "devCupPast", dateTime: new Date("2025-07-13T18:00:00.000Z"), location: "North Stadium", getTeamsFrom: { home: { matchNumber: 29 }, away: { matchNumber: 30 } } },
];

// Dev Euro Cup (future) — 24 teams, no results yet, dates in 2027
// Groups: A (England, France, Germany, Spain)
//         B (Brazil, Argentina, Italy, Netherlands)
//         C (Portugal, Belgium, Croatia, Denmark)
//         D (Japan, Morocco, South Korea, Australia)
//         E (Uruguay, Colombia, Senegal, Sweden)
//         F (Poland, Switzerland, Scotland, Serbia)
// Top 2 from each group + best 4 third-place → R16 (16 teams)
// R16 bracket: A1vM1*, B1vM2*, E1vF2, F1vE2, C1vD2, D1vC2, M3*vA2, M4*vB2
//   (* = groupMatrix.devCup3rdPlace slot, resolved by matrix in competition)
// R16→QF→SF→Final

const future = [
  // ── Group A ──────────────────────────────────────────────────────────────
  { matchNumber: 101, round: 1, type: "Group", groupName: "A", homeTeamName: "England",     awayTeamName: "Germany",      matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-11T13:00:00.000Z"), location: "Wembley Stadium, London" },
  { matchNumber: 102, round: 1, type: "Group", groupName: "A", homeTeamName: "France",      awayTeamName: "Spain",        matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-11T16:00:00.000Z"), location: "Stade de France, Paris" },
  { matchNumber: 103, round: 2, type: "Group", groupName: "A", homeTeamName: "England",     awayTeamName: "Spain",        matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-15T13:00:00.000Z"), location: "Wembley Stadium, London" },
  { matchNumber: 104, round: 2, type: "Group", groupName: "A", homeTeamName: "Germany",     awayTeamName: "France",       matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-15T16:00:00.000Z"), location: "Allianz Arena, Munich" },
  { matchNumber: 105, round: 3, type: "Group", groupName: "A", homeTeamName: "England",     awayTeamName: "France",       matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-19T16:00:00.000Z"), location: "Wembley Stadium, London" },
  { matchNumber: 106, round: 3, type: "Group", groupName: "A", homeTeamName: "Spain",       awayTeamName: "Germany",      matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-19T16:00:00.000Z"), location: "Santiago Bernabeu, Madrid" },
  // ── Group B ──────────────────────────────────────────────────────────────
  { matchNumber: 107, round: 1, type: "Group", groupName: "B", homeTeamName: "Brazil",      awayTeamName: "Italy",        matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-12T13:00:00.000Z"), location: "Maracana, Rio de Janeiro" },
  { matchNumber: 108, round: 1, type: "Group", groupName: "B", homeTeamName: "Argentina",   awayTeamName: "Netherlands",  matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-12T16:00:00.000Z"), location: "Estadio Monumental, Buenos Aires" },
  { matchNumber: 109, round: 2, type: "Group", groupName: "B", homeTeamName: "Brazil",      awayTeamName: "Netherlands",  matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-16T13:00:00.000Z"), location: "Maracana, Rio de Janeiro" },
  { matchNumber: 110, round: 2, type: "Group", groupName: "B", homeTeamName: "Italy",       awayTeamName: "Argentina",    matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-16T16:00:00.000Z"), location: "San Siro, Milan" },
  { matchNumber: 111, round: 3, type: "Group", groupName: "B", homeTeamName: "Brazil",      awayTeamName: "Argentina",    matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-20T16:00:00.000Z"), location: "Maracana, Rio de Janeiro" },
  { matchNumber: 112, round: 3, type: "Group", groupName: "B", homeTeamName: "Netherlands", awayTeamName: "Italy",        matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-20T16:00:00.000Z"), location: "Johan Cruyff ArenA, Amsterdam" },
  // ── Group C ──────────────────────────────────────────────────────────────
  { matchNumber: 113, round: 1, type: "Group", groupName: "C", homeTeamName: "Portugal",    awayTeamName: "Croatia",      matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-13T13:00:00.000Z"), location: "Estadio da Luz, Lisbon" },
  { matchNumber: 114, round: 1, type: "Group", groupName: "C", homeTeamName: "Belgium",     awayTeamName: "Denmark",      matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-13T16:00:00.000Z"), location: "King Baudouin Stadium, Brussels" },
  { matchNumber: 115, round: 2, type: "Group", groupName: "C", homeTeamName: "Portugal",    awayTeamName: "Denmark",      matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-17T13:00:00.000Z"), location: "Estadio da Luz, Lisbon" },
  { matchNumber: 116, round: 2, type: "Group", groupName: "C", homeTeamName: "Croatia",     awayTeamName: "Belgium",      matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-17T16:00:00.000Z"), location: "Maksimir Stadium, Zagreb" },
  { matchNumber: 117, round: 3, type: "Group", groupName: "C", homeTeamName: "Portugal",    awayTeamName: "Belgium",      matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-21T16:00:00.000Z"), location: "Estadio da Luz, Lisbon" },
  { matchNumber: 118, round: 3, type: "Group", groupName: "C", homeTeamName: "Denmark",     awayTeamName: "Croatia",      matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-21T16:00:00.000Z"), location: "Parken Stadium, Copenhagen" },
  // ── Group D ──────────────────────────────────────────────────────────────
  { matchNumber: 119, round: 1, type: "Group", groupName: "D", homeTeamName: "Japan",       awayTeamName: "South Korea",  matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-14T13:00:00.000Z"), location: "Japan National Stadium, Tokyo" },
  { matchNumber: 120, round: 1, type: "Group", groupName: "D", homeTeamName: "Morocco",     awayTeamName: "Australia",    matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-14T16:00:00.000Z"), location: "Stade Ibn Batouta, Tangier" },
  { matchNumber: 121, round: 2, type: "Group", groupName: "D", homeTeamName: "Japan",       awayTeamName: "Australia",    matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-18T13:00:00.000Z"), location: "Japan National Stadium, Tokyo" },
  { matchNumber: 122, round: 2, type: "Group", groupName: "D", homeTeamName: "South Korea", awayTeamName: "Morocco",      matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-18T16:00:00.000Z"), location: "Seoul World Cup Stadium" },
  { matchNumber: 123, round: 3, type: "Group", groupName: "D", homeTeamName: "Japan",       awayTeamName: "Morocco",      matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-22T16:00:00.000Z"), location: "Japan National Stadium, Tokyo" },
  { matchNumber: 124, round: 3, type: "Group", groupName: "D", homeTeamName: "Australia",   awayTeamName: "South Korea",  matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-22T16:00:00.000Z"), location: "Stadium Australia, Sydney" },
  // ── Group E ──────────────────────────────────────────────────────────────
  { matchNumber: 125, round: 1, type: "Group", groupName: "E", homeTeamName: "Uruguay",     awayTeamName: "Senegal",      matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-12T13:00:00.000Z"), location: "Estadio Centenario, Montevideo" },
  { matchNumber: 126, round: 1, type: "Group", groupName: "E", homeTeamName: "Colombia",    awayTeamName: "Sweden",       matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-12T16:00:00.000Z"), location: "Estadio El Campin, Bogota" },
  { matchNumber: 127, round: 2, type: "Group", groupName: "E", homeTeamName: "Uruguay",     awayTeamName: "Sweden",       matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-16T13:00:00.000Z"), location: "Estadio Centenario, Montevideo" },
  { matchNumber: 128, round: 2, type: "Group", groupName: "E", homeTeamName: "Senegal",     awayTeamName: "Colombia",     matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-16T16:00:00.000Z"), location: "Stade Leopold Sedar Senghor, Dakar" },
  { matchNumber: 129, round: 3, type: "Group", groupName: "E", homeTeamName: "Uruguay",     awayTeamName: "Colombia",     matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-20T16:00:00.000Z"), location: "Estadio Centenario, Montevideo" },
  { matchNumber: 130, round: 3, type: "Group", groupName: "E", homeTeamName: "Sweden",      awayTeamName: "Senegal",      matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-20T16:00:00.000Z"), location: "Friends Arena, Stockholm" },
  // ── Group F ──────────────────────────────────────────────────────────────
  { matchNumber: 131, round: 1, type: "Group", groupName: "F", homeTeamName: "Poland",      awayTeamName: "Scotland",     matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-13T13:00:00.000Z"), location: "PGE Narodowy, Warsaw" },
  { matchNumber: 132, round: 1, type: "Group", groupName: "F", homeTeamName: "Switzerland", awayTeamName: "Serbia",       matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-13T16:00:00.000Z"), location: "Wankdorf Stadium, Bern" },
  { matchNumber: 133, round: 2, type: "Group", groupName: "F", homeTeamName: "Poland",      awayTeamName: "Serbia",       matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-17T13:00:00.000Z"), location: "PGE Narodowy, Warsaw" },
  { matchNumber: 134, round: 2, type: "Group", groupName: "F", homeTeamName: "Scotland",    awayTeamName: "Switzerland",  matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-17T16:00:00.000Z"), location: "Hampden Park, Glasgow" },
  { matchNumber: 135, round: 3, type: "Group", groupName: "F", homeTeamName: "Poland",      awayTeamName: "Switzerland",  matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-21T16:00:00.000Z"), location: "PGE Narodowy, Warsaw" },
  { matchNumber: 136, round: 3, type: "Group", groupName: "F", homeTeamName: "Serbia",      awayTeamName: "Scotland",     matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-21T16:00:00.000Z"), location: "Rajko Mitic Stadium, Belgrade" },
  // ── Round of 16 (round=1) ────────────────────────────────────────────────
  // Definite group-position slots
  { matchNumber: 139, round: 1, type: "Playoff", homeTeamName: "Winner Group E",    awayTeamName: "Runner Up Group F", matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-29T15:00:00.000Z"), location: "Friends Arena, Stockholm",          getTeamsFrom: { home: { groupName: "E", position: 1 }, away: { groupName: "F", position: 2 } } },
  { matchNumber: 140, round: 1, type: "Playoff", homeTeamName: "Winner Group F",    awayTeamName: "Runner Up Group E", matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-29T18:00:00.000Z"), location: "PGE Narodowy, Warsaw",              getTeamsFrom: { home: { groupName: "F", position: 1 }, away: { groupName: "E", position: 2 } } },
  { matchNumber: 141, round: 1, type: "Playoff", homeTeamName: "Winner Group C",    awayTeamName: "Runner Up Group D", matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-30T15:00:00.000Z"), location: "Estadio da Luz, Lisbon",            getTeamsFrom: { home: { groupName: "C", position: 1 }, away: { groupName: "D", position: 2 } } },
  { matchNumber: 142, round: 1, type: "Playoff", homeTeamName: "Winner Group D",    awayTeamName: "Runner Up Group C", matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-30T18:00:00.000Z"), location: "Japan National Stadium, Tokyo",     getTeamsFrom: { home: { groupName: "D", position: 1 }, away: { groupName: "C", position: 2 } } },
  // groupMatrix slots — which 3rd-place team fills each slot resolved by matrix
  { matchNumber: 137, round: 1, type: "Playoff", homeTeamName: "Winner Group A",    awayTeamName: "Best 3rd Place",    matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-28T15:00:00.000Z"), location: "Wembley Stadium, London",           getTeamsFrom: { home: { groupName: "A", position: 1 }, away: { groupName: "groupMatrix.devCup3rdPlace" } } },
  { matchNumber: 138, round: 1, type: "Playoff", homeTeamName: "Winner Group B",    awayTeamName: "Best 3rd Place",    matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-06-28T18:00:00.000Z"), location: "Maracana, Rio de Janeiro",          getTeamsFrom: { home: { groupName: "B", position: 1 }, away: { groupName: "groupMatrix.devCup3rdPlace" } } },
  { matchNumber: 143, round: 1, type: "Playoff", homeTeamName: "Best 3rd Place",    awayTeamName: "Runner Up Group A", matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-07-01T15:00:00.000Z"), location: "Estadio Monumental, Buenos Aires",  getTeamsFrom: { home: { groupName: "groupMatrix.devCup3rdPlace" }, away: { groupName: "A", position: 2 } } },
  { matchNumber: 144, round: 1, type: "Playoff", homeTeamName: "Best 3rd Place",    awayTeamName: "Runner Up Group B", matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-07-01T18:00:00.000Z"), location: "San Siro, Milan",                   getTeamsFrom: { home: { groupName: "groupMatrix.devCup3rdPlace" }, away: { groupName: "B", position: 2 } } },
  // ── Quarter Finals (round=2) ─────────────────────────────────────────────
  { matchNumber: 145, round: 2, type: "Playoff", homeTeamName: "Winner 137", awayTeamName: "Winner 138", matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-07-05T15:00:00.000Z"), location: "Wembley Stadium, London",           getTeamsFrom: { home: { matchNumber: 137 }, away: { matchNumber: 138 } } },
  { matchNumber: 146, round: 2, type: "Playoff", homeTeamName: "Winner 139", awayTeamName: "Winner 140", matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-07-05T18:00:00.000Z"), location: "Friends Arena, Stockholm",          getTeamsFrom: { home: { matchNumber: 139 }, away: { matchNumber: 140 } } },
  { matchNumber: 147, round: 2, type: "Playoff", homeTeamName: "Winner 141", awayTeamName: "Winner 142", matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-07-06T15:00:00.000Z"), location: "Estadio da Luz, Lisbon",            getTeamsFrom: { home: { matchNumber: 141 }, away: { matchNumber: 142 } } },
  { matchNumber: 148, round: 2, type: "Playoff", homeTeamName: "Winner 143", awayTeamName: "Winner 144", matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-07-06T18:00:00.000Z"), location: "Maracana, Rio de Janeiro",          getTeamsFrom: { home: { matchNumber: 143 }, away: { matchNumber: 144 } } },
  // ── Semi Finals (round=3) ────────────────────────────────────────────────
  { matchNumber: 149, round: 3, type: "Playoff", homeTeamName: "Winner 145", awayTeamName: "Winner 146", matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-07-11T18:00:00.000Z"), location: "Wembley Stadium, London",           getTeamsFrom: { home: { matchNumber: 145 }, away: { matchNumber: 146 } } },
  { matchNumber: 150, round: 3, type: "Playoff", homeTeamName: "Winner 147", awayTeamName: "Winner 148", matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-07-12T18:00:00.000Z"), location: "Estadio da Luz, Lisbon",            getTeamsFrom: { home: { matchNumber: 147 }, away: { matchNumber: 148 } } },
  // ── Final (round=4) ──────────────────────────────────────────────────────
  { matchNumber: 151, round: 4, type: "Playoff", homeTeamName: "Winner 149", awayTeamName: "Winner 150", matchAccepted: false, sport: "Soccer", bracketCode: "devCupFuture", dateTime: new Date("2027-07-18T18:00:00.000Z"), location: "Wembley Stadium, London",           getTeamsFrom: { home: { matchNumber: 149 }, away: { matchNumber: 150 } } },
];

// Dev Spring Cup (active) — group stage complete, knockouts upcoming
// Groups: A (Brazil, France, Germany) | B (Argentina, Spain, Italy)
// Standings: A1=Brazil A2=France | B1=Argentina B2=Spain
// SF: A1vB2, B1vA2 | Final: winner(207)v winner(208)

const active = [
  // ── Group A ──────────────────────────────────────────────────────────────
  { matchNumber: 201, round: 1, type: "Group", groupName: "A", homeTeamName: "Brazil",    awayTeamName: "Germany",   homeTeamGoals: 2, awayTeamGoals: 0, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupActive", dateTime: new Date("2026-04-05T15:00:00.000Z"), location: "Maracana, Rio de Janeiro" },
  { matchNumber: 202, round: 2, type: "Group", groupName: "A", homeTeamName: "Brazil",    awayTeamName: "France",    homeTeamGoals: 1, awayTeamGoals: 0, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupActive", dateTime: new Date("2026-04-08T15:00:00.000Z"), location: "Maracana, Rio de Janeiro" },
  { matchNumber: 203, round: 3, type: "Group", groupName: "A", homeTeamName: "France",    awayTeamName: "Germany",   homeTeamGoals: 2, awayTeamGoals: 1, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupActive", dateTime: new Date("2026-04-11T15:00:00.000Z"), location: "Stade de France, Paris" },
  // ── Group B ──────────────────────────────────────────────────────────────
  { matchNumber: 204, round: 1, type: "Group", groupName: "B", homeTeamName: "Argentina", awayTeamName: "Italy",     homeTeamGoals: 1, awayTeamGoals: 0, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupActive", dateTime: new Date("2026-04-05T18:00:00.000Z"), location: "Estadio Monumental, Buenos Aires" },
  { matchNumber: 205, round: 2, type: "Group", groupName: "B", homeTeamName: "Argentina", awayTeamName: "Spain",     homeTeamGoals: 2, awayTeamGoals: 1, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupActive", dateTime: new Date("2026-04-08T18:00:00.000Z"), location: "Estadio Monumental, Buenos Aires" },
  { matchNumber: 206, round: 3, type: "Group", groupName: "B", homeTeamName: "Spain",     awayTeamName: "Italy",     homeTeamGoals: 1, awayTeamGoals: 0, matchAccepted: true,  sport: "Soccer", bracketCode: "devCupActive", dateTime: new Date("2026-04-11T18:00:00.000Z"), location: "Santiago Bernabeu, Madrid" },
  // ── Semi Finals (round=1) ────────────────────────────────────────────────
  { matchNumber: 207, round: 1, type: "Playoff", homeTeamName: "Brazil",    awayTeamName: "Spain",   matchAccepted: false, sport: "Soccer", bracketCode: "devCupActive", dateTime: new Date("2026-12-20T15:00:00.000Z"), location: "Maracana, Rio de Janeiro",          getTeamsFrom: { home: { groupName: "A", position: 1 }, away: { groupName: "B", position: 2 } } },
  { matchNumber: 208, round: 1, type: "Playoff", homeTeamName: "Argentina", awayTeamName: "France",  matchAccepted: false, sport: "Soccer", bracketCode: "devCupActive", dateTime: new Date("2026-12-20T18:00:00.000Z"), location: "Estadio Monumental, Buenos Aires",  getTeamsFrom: { home: { groupName: "B", position: 1 }, away: { groupName: "A", position: 2 } } },
  // ── Final (round=2) ──────────────────────────────────────────────────────
  { matchNumber: 209, round: 2, type: "Playoff", homeTeamName: "Winner 207",       awayTeamName: "Winner 208",     matchAccepted: false, sport: "Soccer", bracketCode: "devCupActive", dateTime: new Date("2026-12-27T18:00:00.000Z"), location: "Wembley Stadium, London",           getTeamsFrom: { home: { matchNumber: 207 }, away: { matchNumber: 208 } } },
];

module.exports = [...active, ...past, ...future];
